<?php

namespace AppBundle\Repository;

/**
 * ImgPagareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgPagareRepository extends \Doctrine\ORM\EntityRepository
{
}
